version: "3.8"
services:
  nginx:
    container_name: test_nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src:/var/www/html
  php:
    container_name: test_php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    environment:
      ROOT_PATH: /var/www/html
      DB_USERNAME_DEV: root
      DB_PASSWORD_DEV: +6fIyU0o1*+Wexic
      DB_USERNAME_PROD: <production database user name>
      DB_PASSWORD_PROD: <production database user password>
